server:
  port: 9014
spring:
  application:
    name: tensquare-notice
  datasource:
    url: jdbc:mysql://192.168.137.140:3306/tensquare_notice?charaterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.137.140
  rabbitmq:
    host: 192.168.137.140
# Mybatis-Plus 配置
mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tensquare.notice.pojo
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句, 开发中用，发布时不能用
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true