server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    url: jdbc:mysql://192.168.137.140:3306/tensquare_article?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  data:
    mongodb:
      database: commentdb
      host: 192.168.137.140
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.137.140
  rabbitmq:
    host: 192.168.137.140
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
# Mybatis-Plus 配置
mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tensquare.article.pojo
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句, 开发中用，发布时不能用
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true #实体类属性驼峰命名规则
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #是否允许单一语句返回多结果集（需要兼容驱动）
